//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 53b46715-1996-467c-8d40-7e8d48246726 aws-my-sample-app-android-v0.7";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:196410d9-6c6c-4636-9269-e4d9b8ef9414";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "2daf57722d4d439fb8debd2f26a38733";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    // Google Client ID for Web application
    public static final String GOOGLE_CLIENT_ID =
        "713730867071-am8qmlc6t1j9p29p8s5f2941q217dejb.apps.googleusercontent.com";
    // GOOGLE CLOUD MESSAGING API KEY
    public static final String GOOGLE_CLOUD_MESSAGING_API_KEY =
        "AIzaSyBkltm-TiUVI8mXvdVW8p1qQW8JT1-IiuQ";
    // GOOGLE CLOUD MESSAGING SENDER ID
    public static final String GOOGLE_CLOUD_MESSAGING_SENDER_ID =
        "713730867071";

    // SNS PLATFORM APPLICATION ARN
    public static final String AMAZON_SNS_PLATFORM_APPLICATION_ARN =
        "arn:aws:sns:us-east-1:281681423403:app/GCM/angleapp_MOBILEHUB_1491286053";
    // SNS DEFAULT TOPIC ARN
    public static final String AMAZON_SNS_DEFAULT_TOPIC_ARN =
        "arn:aws:sns:us-east-1:281681423403:angleapp_alldevices_MOBILEHUB_1491286053";
    // SNS PLATFORM TOPIC ARNS
    public static final String[] AMAZON_SNS_TOPIC_ARNS =
        {"arn:aws:sns:us-east-1:281681423403:asa","arn:aws:sns:us-east-1:281681423403:angleapp_welcome_MOBILEHUB_1491286053"};
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "angleapp-contentdelivery-mobilehub-1491286053";
    public static final String AMAZON_CLOUD_FRONT_DISTRIBUTION_DOMAIN =
        "drkxshd17fjkf.cloudfront.net";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "angleapp-userfiles-mobilehub-1491286053";
}
